[package]
name = "svg2pdf"
version = "0.1.0"
edition = "2018"
license = "MIT OR Apache-2.0"

[features]
default = ["png", "jpeg"]
png = ["image/png"]
jpeg = ["image/jpeg"]

[dependencies]
image = { version = "0.23", default-features = false, optional = true }
miniz_oxide = "0.4"
pdf-writer = { git = "https://github.com/typst/pdf-writer", rev = "a8880b6" }
usvg = "0.19"
